name: User server Node.js CI

on:
  push:
    branches: [ "master" ]

jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [14.x] # Adjust the Node.js version accordingly

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
      env:
        PROD_ENV: ${{ secrets.PROD_ENV }}
    - run: |
        echo "PROD_ENV=${PROD_ENV}" > .env
        npm ci
